name = "skoon-interview-agent"
compatibility_date = "2024-09-23"
pages_build_output_dir = "."

[[kv_namespaces]]
binding = "SKOON_INTERVIEWS"
id = "e6eb84d2e7194511a65d9f73ef75c11d"
preview_id = "e6eb84d2e7194511a65d9f73ef75c11d"
